# Generated by Django 4.1.5 on 2023-02-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
