# Generated by Django 4.1.5 on 2023-02-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0032_merge_20230204_0058'),
        ('approval', '0002_approval_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='card.card'),
            preserve_default=False,
        ),
    ]
