# Generated by Django 4.1.5 on 2023-02-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_approval_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.approval'),
        ),
    ]
