# Generated by Django 4.1.5 on 2023-02-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_alter_approval_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='card',
            new_name='card_ref',
        ),
    ]
