# Generated by Django 4.1.7 on 2023-02-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_rename_card_approval_card_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approving_position',
            field=models.CharField(choices=[('OPERATOR', 'Оператор'), ('LEAD_ENGINEER', 'Ведущий инженер'), ('HEAD_SERVICE', 'Начальник службы'), ('HEAD_SCPE', 'Начальник СКПЭ'), ('OPERATOR_SCPE', 'Оператор СКПЭ'), ('CONTROLLER', 'Контроллер')], default='OPERATOR', max_length=30),
        ),
    ]
