version: "3.8"

services:
  web_project_arec:
    build: .
    image: app
    depends_on:
      - postgres    
    # command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/code
    entrypoint:
      - ./entrypoint.sh
    ports:
      - "8000:8000"

  postgres:
    image: postgres:latest
    env_file: ./arec/environments/dev.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
      restart: always
      depends_on:
        - web_project_arec
      build:
          context: ./nginx
      ports:
      - "80:80"
      volumes:
        - ./files:/code/files
        - /usr/django-admin-static-files/static/admin:/usr/django-admin-static-files/static/admin
        - ./arec/static:/code/arec/static

volumes:
  pg_data: {}
