version: "3.8"

services:
  web_project_arec:
    build: .
    image: app
    # command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/code
    entrypoint:
      - ./entrypoint.sh
    ports:
      - "8000:8000"

  nginx:
      restart: always
      build:
          context: ./nginx
      ports:
      - "80:80"
      volumes:
        - ./files:/code/files
        - ./arec/static:/code/arec/static
