# Generated by Django 4.1.5 on 2023-01-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic_name', models.CharField(max_length=50)),
                ('phone_number', models.PositiveIntegerField()),
                ('district', models.CharField(max_length=125)),
                ('street', models.CharField(max_length=125)),
                ('bldg', models.CharField(max_length=8)),
                ('block', models.CharField(max_length=8)),
                ('apt_num', models.CharField(max_length=6)),
                ('floor', models.PositiveIntegerField()),
                ('entrance', models.PositiveSmallIntegerField(default=1)),
                ('square', models.DecimalField(decimal_places=2, max_digits=6)),
                ('connection_point', models.CharField(max_length=125)),
                ('power', models.CharField(max_length=8)),
                ('nominal', models.PositiveSmallIntegerField()),
                ('main_point', models.CharField(max_length=125)),
                ('counter_number', models.CharField(max_length=25)),
                ('counter_model', models.CharField(max_length=50)),
                ('contract', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=250)),
                ('operator', models.CharField(max_length=250)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
