# Generated by Django 4.1.5 on 2023-01-22 23:04

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(choices=[('contract', 'Договор на помещение'), ('tech_passport', 'Технический паспорт'), ('identification', 'Удостоверение личности'), ('tech_condition', 'Техническое условие'), ('dividing_act', 'Акт раздела границы'), ('others', 'Другие документы')], max_length=15)),
                ('doc_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/code/files'), upload_to='docs/%Y/%m/%d/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.docscan'),
        ),
    ]
