# Generated by Django 4.1.5 on 2023-01-24 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_docscan_card_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-created_at']},
        ),
    ]
