# Generated by Django 4.1.5 on 2023-01-24 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='files',
        ),
        migrations.AddField(
            model_name='docscan',
            name='card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='card.card'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docscan',
            name='doctype',
            field=models.CharField(choices=[('realty_contract', 'Договор на помещение'), ('tech_passport', 'Технический паспорт'), ('identification', 'Удостоверение личности'), ('tech_condition', 'Техническое условие'), ('dividing_act', 'Акт раздела границы'), ('others', 'Другие документы')], max_length=15),
        ),
    ]
