# Generated by Django 4.1.5 on 2023-01-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_remove_card_files_docscan_card_alter_docscan_doctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CardLegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='patronymic_name',
        ),
        migrations.AddField(
            model_name='card',
            name='OBJECT_CATEGORY',
            field=models.CharField(blank=True, choices=[('test', 'test')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='task',
            field=models.CharField(blank=True, choices=[('test', 'test')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='individual_entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.cardindividual'),
        ),
        migrations.AddField(
            model_name='card',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.cardlegalentity', unique=True),
        ),
    ]
