# Generated by Django 4.1.5 on 2023-01-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_rename_object_category_card_object_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='individual_entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individuals', to='card.cardindividual'),
        ),
        migrations.AlterField(
            model_name='card',
            name='legal_entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_entities', to='card.cardlegalentity'),
        ),
    ]
