# Generated by Django 4.1.5 on 2023-01-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_card_individual_entity_alter_card_legal_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='individual_entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.cardindividual'),
        ),
        migrations.AlterField(
            model_name='card',
            name='legal_entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.cardlegalentity'),
        ),
    ]
