# Generated by Django 4.1.5 on 2023-01-27 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_alter_card_individual_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='iin',
            field=models.CharField(default=None, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Введите корректный иин')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='object_category',
            field=models.CharField(blank=True, choices=[('garage', 'Гараж'), ('house', 'Дом'), ('office', 'Офис'), ('production base', 'Производственная база'), ('other', 'Иное')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='task',
            field=models.CharField(blank=True, choices=[('change of ownership', 'Cмена владельца'), ('initial registration', 'Первичная регистрация'), ('other', 'Иное')], max_length=60, null=True),
        ),
    ]
