# Generated by Django 4.1.5 on 2023-01-27 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_alter_card_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='iin',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Введите корректный иин')]),
        ),
    ]
