# Generated by Django 4.1.5 on 2023-01-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_alter_card_iin'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='city',
            field=models.CharField(default=None, max_length=125),
            preserve_default=False,
        ),
    ]
