# Generated by Django 4.1.5 on 2023-01-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_card_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='object_category',
            field=models.CharField(blank=True, choices=[('Гараж', 'Гараж'), ('Дом', 'Дом'), ('Офис', 'Офис'), ('Производственная база', 'Производственная база'), ('Иное', 'Иное')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='task',
            field=models.CharField(blank=True, choices=[('Cмена владельца', 'Cмена владельца'), ('Первичная регистрация', 'Первичная регистрация'), ('Иное', 'Иное')], max_length=60, null=True),
        ),
    ]
