# Generated by Django 4.1.5 on 2023-01-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_alter_card_object_category_alter_card_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
