# Generated by Django 4.1.5 on 2023-01-29 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_alter_card_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='iin',
        ),
        migrations.AddField(
            model_name='cardindividual',
            name='iin',
            field=models.CharField(default=0, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Введите корректный ИИН')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardlegalentity',
            name='bin',
            field=models.CharField(default=0, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Введите корректный БИН')]),
            preserve_default=False,
        ),
    ]
