# Generated by Django 4.1.5 on 2023-01-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_remove_card_iin_cardindividual_iin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
