# Generated by Django 4.1.5 on 2023-01-29 23:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0018_alter_card_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='file',
            field=models.FileField(default=1, storage=django.core.files.storage.FileSystemStorage(location='/code/files'), upload_to='docs/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocScan',
        ),
    ]
