# Generated by Django 4.1.5 on 2023-01-30 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0019_card_file_delete_docscan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='file',
            new_name='docsan',
        ),
    ]
