# Generated by Django 4.1.5 on 2023-01-30 07:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0020_rename_file_card_docsan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='docsan',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/code/files'), upload_to='docs/%Y/%m/%d/'),
        ),
    ]
