# Generated by Django 4.1.5 on 2023-01-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0021_alter_card_docsan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='docsan',
            new_name='file',
        ),
    ]
