# Generated by Django 4.1.5 on 2023-01-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0028_alter_card_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='object_category',
            field=models.CharField(blank=True, choices=[('Garage', 'Гараж'), ('House', 'Дом'), ('Office', 'Офис'), ('Industrial_base', 'Производственная база'), ('Other', 'Иное')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='task',
            field=models.CharField(blank=True, choices=[('Change_of_owner', 'Cмена владельца'), ('Primary_registration', 'Первичная регистрация'), ('Other', 'Иное')], max_length=60, null=True),
        ),
    ]
