# Generated by Django 4.1.5 on 2023-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0029_alter_card_object_category_alter_card_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='received_at',
            field=models.DateTimeField(default="2013-01-01 01:00:00 +00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
