# Generated by Django 4.1.5 on 2023-02-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0031_alter_card_district'),
        ('card', '0031_card_is_archived_alter_card_district'),
    ]

    operations = [
    ]
