# Generated by Django 4.1.5 on 2023-02-07 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_rename_card_approval_card_ref'),
        ('card', '0032_merge_20230204_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_approval',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.approval'),
        ),
    ]
