# Generated by Django 4.1.7 on 2023-02-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0034_alter_card_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='page_number_on_which_the_act_begins',
            field=models.IntegerField(null=True),
        ),
    ]
