# Generated by Django 4.1.7 on 2023-02-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0035_card_page_number_on_which_the_act_begins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='page_number_on_which_the_act_begins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
