# Generated by Django 4.1.7 on 2023-02-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0036_alter_card_page_number_on_which_the_act_begins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='page_number_on_which_the_act_begins',
            new_name='act_page_number',
        ),
    ]
