xl_map = {
    # 'A': 'created_at',
    # 'B': 'created_at',
    'C': 'city',
    'D': 'district',
    'E': 'street',
    'F': 'bldg',
    'G': 'block',
    'H': 'entrance',
    'I': 'floor',
    'J': 'apt_num',
    'K': 'individual_entity__last_name',
    'L': 'individual_entity__first_name',
    'M': 'individual_entity__patronymic_name',
    'N': 'individual_entity__iin',
    'O': 'phone_number',
    'P': 'object_category',
    'Q': 'square',
    'R': 'connection_point',
    'S': 'power',
    'T': 'nominal',
    'U': 'main_point',
    'V': 'counter_model',
    'W': 'counter_number',
    'X': 'contract',
    'Y': 'organization',
}
