# Generated by Django 4.1.5 on 2023-02-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(choices=[('almaty', 'Алматы'), ('baikonur', 'Байконур'), ('esil', 'Есиль'), ('nura', 'Нура'), ('saryarka', 'Сарыарка')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('OPERATOR', 'Оператор'), ('LEAD_ENGINEER', 'Ведущий инженер'), ('HEAD_SERVICE', 'Начальник службы'), ('HEAD_SCPE', 'Начальник СКПЭ'), ('CONTROLLER', 'Контроллер')], max_length=30),
        ),
    ]
