# Generated by Django 4.1.5 on 2023-01-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('OPERATOR', 'ОПЕРАТОР'), ('LEAD_ENGINEER', 'ВЕДУЩИЙ ИНЖЕНЕР'), ('HEAD_SERVICE', 'НАЧАЛЬНИК СЛУЖБЫ'), ('HEAD_SCPE', 'НАЧАЛЬНИК СКПЭ'), ('CONTROLLER', 'КОНТРОЛЛЕР')], max_length=30, verbose_name='Должность'),
        ),
    ]
