# Generated by Django 4.1.6 on 2023-02-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_position'),
        ('users', '0003_user_district_alter_user_position'),
    ]

    operations = [
    ]
